name: Test deploy                    
on:                                  
  push:
    branches:
      - build/*                        
jobs:                               
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Check Node version   
        run: node -v
        
      - name: Install dependencies 
        run: npm install
      
      - name: Generate build 
        run: npm run build
        
      - name: Where is output? 
        run: ls build/
      - name: Where is it? 
        run: pwd
        
      - name: Where is it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.SCP_PORT }}
          script: |
            ls
            pwd
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.SCP_PORT }}
          source: build/*
          target: /home/${{ secrets.DEPLOY_USER }}/react
